### ISSUE TITLE
Remove explicit ?versionHistoryGraph value from generic skos-history queries

### ISSUE THREAD

**Issue by jneubert** [jneubert/skos-history#25]
The queries in https://github.com/jneubert/skos-history/tree/master/sparql are intented to work with any skos vocabulary. However, they currently rely on an explicit setting of the ?versionHistoryGraph variable (defaulting to `https://zbw.eu/stw/version`). This is unfortunate, because for ervery re-use with another vocabulary, the according VALUES parameter has to be replaced.

Binding ?versionHistoryGraph explicitely should not be necessary at all, if we start with a statement such as:
```
  GRAPH ?versionHistoryGraph {
    ?vhr dsv:hasVersionHistorySet ?vhs .
    # ...
  }
```
The property `dsv:hasVersionHistorySet` is only expected in a version history graph, which should be unique in an endpoint with multiple versions of the same concept scheme, so normally that should be save. If an endpoint configuration with versions of different datasets and multiple version history graphs is used, the query could be extended by binding to an explicit value of ?versionHistoryGraph anyway.

@osma - what do you think?

**Comment by jneubert** [comment]
Example in http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/version_overview.rq

**Comment by jneubert** [comment]
For selection of the ?versionHistoryGraph, perhaps better use:
```
  GRAPH ?versionHistoryGraph {
    ?vhs dsv:currentVersionRecord [] .
````
That should look for exactly one triple.

**Comment by jneubert** [comment]
For better backward compatibility, and as a hint, that the version history set optionally _can_ be set as a parameter, we could set `?versionHistorySet` to `undef` (as already suggested in the [boilerplate template](https://github.com/jneubert/skos-history/blob/master/sparql/_template.rq)).

**Comment by osma** [comment]
+1 for keeping `?versionHistorySet` in the VALUES block but leaving it as `undef`.

I currently store both YSA and Allärs snapshots in the same skos-history repository, though I would expect this kind of multi-vocabulary usage to be rare.
